"""Add job_type

Revision ID: 85094035cce5
Revises: ff3fcf988fab
Create Date: 2025-11-22 13:34:03.331640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85094035cce5'
down_revision: Union[str, Sequence[str], None] = 'ff3fcf988fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_column('jobs', 'job_type')
    # ### end Alembic commands ###
